---
title: "minnemudac"
author: "Federico Chung"
date: "10/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE)
library(dplyr)
library(lubridate)
library(stringr)
library(ggplot2)
library(astsa)
library(splines)
library(tidyr)
library(naniar)
library(BBmisc)
library(gam)
```

```{r}
historical.prices<-read.csv("historical_soybean_prices.csv")
```

```{r}
#clean the data
historical.prices<-
  historical.prices%>%
  separate("date",c("Month","Day","Year"))

first_part<-historical.prices[1:7828,]
View(first_part)

second_part<-historical.prices[7829:nrow(historical.prices),]

first_part<-
  first_part%>%
  mutate(Year = as.numeric(Year)+1900)
second_part<-
  second_part%>%
  mutate(Year = as.numeric(Year)+2000)
historical.prices<- rbind(first_part,second_part)
  
historical.prices<-
  historical.prices%>%
  mutate(Date = paste(Year,Month,Day, sep ="/"))%>%
  mutate(Date = as.Date(Date))


max(historical.prices$Date, na.rm = TRUE)

date_begin <- as.Date("1968/12/05", tryFormats = c("%Y/%m/%d"))
date_end <- as.Date("2019/10/25", tryFormats = c("%Y/%m/%d"))


historical.prices <-
  historical.prices%>%
  complete(Date = seq.Date(date_begin, date_end, by="day"))

historical.prices<-
  historical.prices%>%
  mutate(Month = month(Date))%>%
  mutate(Day = day(Date))%>%
  mutate(Year = year(Date))%>%
  mutate(wday = wday(Date))

write.csv(historical.prices, "soybeans.csv")
```


```{r}
#ts is hard because there is not frequent data
prices<-ts(historical.prices$value, start = c(1968,12,05), frequency = 365)

plot(prices)

p1<-historical.prices%>%
  filter(Year>2017)
min(p1$Date)
p1_ts<-ts(p1$value, start = c(2018,01,01),frequency = 365)
plot(p1_ts)

historical.prices$value
```


```{r}
oil<-read.csv("DCOILWTICO.csv")
oil

oil$DCOILWTICO<-as.numeric(as.character(oil$DCOILWTICO))
oil

oil$DCOILWTICO<-na_if(oil$DCOILWTICO,".")

oil$DATE<- as.Date(oil$DATE)
oil

date_begin <- as.Date("1986/01/02", tryFormats = c("%Y/%m/%d"))
date_end<-as.Date("2019/10/21", tryFormats = c("%Y/%m/%d"))

oil <-
  oil%>%
  complete(DATE = seq.Date(date_begin, date_end, by="day"))%>%
  mutate(Month = month(DATE))%>%
  mutate(Day = day(DATE))%>%
  mutate(Year = year(DATE))%>%
  mutate(wday = wday(DATE))


oil$DCOILWTICO<- as.double(oil$DCOILWTICO)
```

```{r}
oil_ts<- ts(oil$DCOILWTICO, start =c(1986,01,02), frequency = 365 )

plot(oil_ts, col = "black")
```

```{r}
#CORRELATION IS NOT CAUSATION
join<-
  historical.prices%>%
  left_join(oil)

join%>%
  filter(Year>1990)

cor(join$value,join$DCOILWTICO, use = "complete.obs")
```

```{r}
ggplot(historical.prices)+
  geom_line(aes(x = Date, y = normalize(value)))+
  geom_line(data = oil, aes(x = DATE, y = normalize(DCOILWTICO), color = "oil"))+
  theme_minimal()+
  ggtitle("Historical Normalized Soybean Prices and Oil Prices")

normalize(historical.prices$value)

LOESS_Soybean<- loess(value ~ decimal_date(Date), data = historical.prices, span = 50/18586)


ggplot(historical.prices_na)+
  geom_line(aes(x = Date, y = value))+
  geom_line(aes(x = Date, y = predict(LOESS_Soybean),color = "Loess"))
```
```{r}

historical.prices

gam_model <- train(
      Grad.Rate~.,
      data = model_data,
      method = "gamLoess",
      tuneGrid = data.frame(span = seq(0.1, 1, length = 10), degree = 1),
      trControl = trainControl(method = "cv", number = 10, selectionFunction = "best"),
      metric = "MAE",
      na.action = na.omit
    )

set.seed(253)
LOESS_Soybean<-
  train(
    value~Date,
    data = historical.prices,
    method = "gamLoess",
    tuneGrid = data.frame(span = seq(0.01, 1, length = 10),degree =1),
    trControl = trainControl(method = "cv", number = 10, selectionFunction = "oneSE"),
    metric = "MAE",
    na.action = na.omit
  )
```


```{r}
library(forecast)
fitma <- auto.arima(prices, max.p=0, stationary=TRUE, seasonal=FALSE)

```


